### ISSUE TITLE
Небольшие правки к материалу

### ISSUE THREAD

**Issue by alyona-good** [i-obraztsov/answers#1]
Привет! Очень познавательный материал, спасибо!

Есть пару неточностей, которые стоит подкорректировать:
Вопрос: 49. Должны ли мы отдавать разные размеры картинок пользователям разных устройств? Если да, то как?

Ответ: Должны. При помощи меда выражений и тёга picture и атрибута srcste у img;
Неточность: в слове "srcste", нужно исправить на srcset.
И слова "медиа" и "тёга" тоже 

Вопрос: 58. Как найти элемент на странице с помощью JS и JQuery?

Ответ: getElementById; getElementsByTagName; getElementsByName; querySelectorAll; querySelector;

Неточность: в "getElementsByName" - ошибка, правильно "getElementsByClassName"

Ещё раз спасибо!
Хорошего дня! :)

**Comment by i-obraztsov** [comment]
Добрый день! Спасибо за замечания) Исправил)
